export const ADMIN_SECTIONS = [
  { id: "dashboard", label: "Dashboard", description: "Overview of sales, stock, and activity." },
  { id: "products", label: "Products", description: "Add products, edit prices, manage categories." },
  { id: "inventory", label: "Inventory", description: "Stock levels and low-stock alerts." },
  { id: "orders", label: "Orders", description: "Pending, shipped, and delivered orders." },
  { id: "customers", label: "Customers", description: "Customer profiles and order history." },
  { id: "payments", label: "Payments", description: "Payment history, refunds, and failed payments." },
  { id: "promotions", label: "Promotions", description: "Create and manage promo campaigns." },
  { id: "urm", label: "Sub-admin Approvals", description: "Approve or reject sub-admin access requests." },
  { id: "analysis", label: "Analysis", description: "Live metrics and recent movement." },
  { id: "suppliers", label: "Suppliers", description: "Supplier contacts and sourcing info." },
  { id: "shipping", label: "Shipping", description: "Delivery zones and courier settings." },
  { id: "marketing", label: "Marketing", description: "Campaigns and outreach." },
  { id: "reviews", label: "Reviews", description: "Customer reviews and ratings." },
  { id: "reports", label: "Reports", description: "Exportable sales and inventory reports." },
  { id: "content", label: "Content", description: "Site content and banners." },
  { id: "notifications", label: "Notifications", description: "Alerts and admin notifications." },
  { id: "support", label: "Support", description: "Customer support messages." },
  { id: "returns", label: "Returns", description: "Return and refund requests." },
  { id: "users", label: "Users", description: "All admin and customer accounts." },
  { id: "settings", label: "Settings", description: "Store, account, and app settings." },
] as const;
