/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminVerifyUnlockUidb64TokenRouteImport } from './routes/admin/verify-unlock.$uidb64.$token'
import { Route as AdminResetPasswordUidb64TokenRouteImport } from './routes/admin/reset-password.$uidb64.$token'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerifyUnlockUidb64TokenRoute =
  AdminVerifyUnlockUidb64TokenRouteImport.update({
    id: '/verify-unlock/$uidb64/$token',
    path: '/verify-unlock/$uidb64/$token',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminResetPasswordUidb64TokenRoute =
  AdminResetPasswordUidb64TokenRouteImport.update({
    id: '/$uidb64/$token',
    path: '/$uidb64/$token',
    getParentRoute: () => AdminResetPasswordRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRouteWithChildren
  '/admin/signup': typeof AdminSignupRoute
  '/admin/reset-password/$uidb64/$token': typeof AdminResetPasswordUidb64TokenRoute
  '/admin/verify-unlock/$uidb64/$token': typeof AdminVerifyUnlockUidb64TokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRouteWithChildren
  '/admin/signup': typeof AdminSignupRoute
  '/admin/reset-password/$uidb64/$token': typeof AdminResetPasswordUidb64TokenRoute
  '/admin/verify-unlock/$uidb64/$token': typeof AdminVerifyUnlockUidb64TokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRouteWithChildren
  '/admin/signup': typeof AdminSignupRoute
  '/admin/reset-password/$uidb64/$token': typeof AdminResetPasswordUidb64TokenRoute
  '/admin/verify-unlock/$uidb64/$token': typeof AdminVerifyUnlockUidb64TokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/signup'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/admin/reset-password/$uidb64/$token'
    | '/admin/verify-unlock/$uidb64/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/signup'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/admin/reset-password/$uidb64/$token'
    | '/admin/verify-unlock/$uidb64/$token'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/signup'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/admin/reset-password/$uidb64/$token'
    | '/admin/verify-unlock/$uidb64/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verify-unlock/$uidb64/$token': {
      id: '/admin/verify-unlock/$uidb64/$token'
      path: '/verify-unlock/$uidb64/$token'
      fullPath: '/admin/verify-unlock/$uidb64/$token'
      preLoaderRoute: typeof AdminVerifyUnlockUidb64TokenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password/$uidb64/$token': {
      id: '/admin/reset-password/$uidb64/$token'
      path: '/$uidb64/$token'
      fullPath: '/admin/reset-password/$uidb64/$token'
      preLoaderRoute: typeof AdminResetPasswordUidb64TokenRouteImport
      parentRoute: typeof AdminResetPasswordRoute
    }
  }
}

interface AdminResetPasswordRouteChildren {
  AdminResetPasswordUidb64TokenRoute: typeof AdminResetPasswordUidb64TokenRoute
}

const AdminResetPasswordRouteChildren: AdminResetPasswordRouteChildren = {
  AdminResetPasswordUidb64TokenRoute: AdminResetPasswordUidb64TokenRoute,
}

const AdminResetPasswordRouteWithChildren =
  AdminResetPasswordRoute._addFileChildren(AdminResetPasswordRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRouteWithChildren
  AdminSignupRoute: typeof AdminSignupRoute
  AdminVerifyUnlockUidb64TokenRoute: typeof AdminVerifyUnlockUidb64TokenRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRouteWithChildren,
  AdminSignupRoute: AdminSignupRoute,
  AdminVerifyUnlockUidb64TokenRoute: AdminVerifyUnlockUidb64TokenRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
