/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSignupRoute: typeof AdminSignupRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSignupRoute: AdminSignupRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
